package com.soft_cafe.biome;

import com.soft_cafe.TSC_Core;
import net.minecraft.world.biome.Biome;

public class BiomeTemperatureRangesLookup {
    public static void LookUp(String biomeName, Biome biome) {
        int monthNumber = TSC_Core.getCalendar().getDisplayMonth();

        switch(biomeName)
        {
            case("mushroom_fields"):
                break;
            case("deep_frozen_ocean"):
                break;
            case("frozen_ocean"):
                break;
            case("deep_cold_ocean"):
                break;
            case("cold_ocean"):
                break;
            case("deep_ocean"):
                break;
            case("ocean"):
                break;
            case("deep_luekwarm_ocean"):
                break;
            case("lukewarm_ocean"):
                break;
            case("warm_ocean"):
                break;
            case("stone_shore"):
                break;
            case("swamp"):
                break;
            case("snowy_slopes"):
                break;
            case("snowy_plains"):
                break;
            case("snowy_beach"):
                break;
            case("windswept_gravelly_hills"):
                break;
            case("grove"):
                break;
            case("windswept_hills"):
                break;
            case("snowy_taiga"):
                switch(monthNumber)
                {
                    case(1):
                        break;
                    case(2):
                        break;
                    case(4):
                        break;
                    case(5):
                        break;
                    case(6):
                        break;
                    case(7):
                        break;
                    case(8):
                        break;
                    case(9):
                        break;
                    case(10):
                        break;
                    case(11):
                        break;
                    case(12):
                        break;
                }
                break;
            case("windswept_forest"):
                break;
            case("taiga"):
                break;
            case("plains"):
                break;
            case("meadow"):
                break;
            case("beach"):
                break;
            case("forest"):
                break;
            case("old_growth_spruce_taiga"):
                break;
            case("flower_forest"):
                break;
            case("birch_forest"):
                break;
            case("dark_forest"):
                break;
            case("savanna_plateau"):
                break;
            case("savanna"):
                break;
            case("jungle"):
                break;
            case("badlands"):
                break;
            case("eroded_badlands"):
                break;
            case("desert"):
                break;
            case("wooded_badlands"):
                break;
            case("jagged_peaks"):
                break;
            case("stony_peaks"):
                break;
            case("frozen_river"):
                break;
            case("river"):
                break;
            case("ice_spikes"):
                break;
            case("old_growth_pine_taiga"):
                break;
            case("sunflower_plains"):
                break;
            case("old_growth_birch_forest"):
                break;
            case("sparse_jungle"):
                break;
            case("bamboo_jungle"):
                break;
            case("windswept_savanna"):
                break;
            case("frozen_peaks"):
                break;
            case("dripstone_caverns"):
                break;
            case("lush_caves"):
                break;
            default:
                break;
        }

        switch(monthNumber)
        {
            case(1):
                break;
            case(2):
                break;
            case(4):
                break;
            case(5):
                break;
            case(6):
                break;
            case(7):
                break;
            case(8):
                break;
            case(9):
                break;
            case(10):
                break;
            case(11):
                break;
            case(12):
                break;
        }
    }
}
